# Generated by Django 4.0.4 on 2022-04-29 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_alter_comment_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
