# Generated by Django 4.0.4 on 2022-05-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_remove_book_categories_category_books_category_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='books',
        ),
        migrations.RemoveField(
            model_name='category',
            name='owner',
        ),
    ]
